CREATE TABLE folder (folder_id INTEGER PRIMARY KEY AUTOINCREMENT, parent_folder_id INTEGER, account_id text DEFAULT '' NOT NULL, name text DEFAULT '' NOT NULL, rights INTEGER DEFAULT 0 NOT NULL , attributes INTEGER DEFAULT 0 NOT NULL , sync CHAR(1), path text DEFAULT '', uid_validity text DEFAULT '', sync_update INTEGER DEFAULT 0 NOT NULL , unseen INTEGER DEFAULT 0 NOT NULL , messages INTEGER DEFAULT 0 NOT NULL , subscription_type text DEFAULT '')
CREATE TABLE item (item_id INTEGER PRIMARY KEY AUTOINCREMENT, folder_id INTEGER NOT NULL, rid text DEFAULT '' NOT NULL, message_id varchar(255) , size INTEGER NOT NULL, date INTEGER NOT NULL, header_from text DEFAULT '' , header_to text DEFAULT '' , header_cc text DEFAULT '', header_bcc text DEFAULT '', header_sms text DEFAULT '', subject text DEFAULT '' , priority INTEGER DEFAULT 0 NOT NULL , flags INTEGER DEFAULT 0 NOT NULL , unread INTEGER DEFAULT 0 NOT NULL , body text DEFAULT '', static_flags INTEGER DEFAULT 0 NOT NULL , smime_status INTEGER DEFAULT 0 NOT NULL , has_attachment VARCHAR(1) DEFAULT 'F' , color VARCHAR(1) DEFAULT 'Z' , completed_on VARCHAR(32),sort_subject text DEFAULT '', sort_from text DEFAULT '', sort_to text DEFAULT '' , sort_cc text DEFAULT '' , sort_bcc text DEFAULT '' , sort_sms text DEFAULT '' , msg_file text DEFAULT '' , flag_update INTEGER DEFAULT 0 NOT NULL , source_folder_id INTEGER , dummy_id INTEGER , is_hidden INTEGER DEFAULT 0 NOT NULL, taglist text DEFAULT '', item_moved INTEGER DEFAULT 0 NOT NULL ) 
CREATE INDEX IDX_folder_account ON folder (account_id,folder_id)
CREATE INDEX IDX_folder_parent ON folder (parent_folder_id)
CREATE INDEX IDX_item_date ON item (folder_id,date)
CREATE INDEX IDX_item_list ON item (folder_id,unread,is_hidden)
CREATE INDEX IDX_item_flag_update ON item (folder_id,flag_update)
CREATE INDEX IDX_item_rid ON item (folder_id,rid)
CREATE INDEX IDX_folder_account ON folder (account_id,folder_id)
CREATE INDEX IDX_folder_parent ON folder (parent_folder_id)
CREATE INDEX IDX_item_date ON item (folder_id,date)
CREATE INDEX IDX_item_list ON item (folder_id,unread,is_hidden)
CREATE INDEX IDX_item_flag_update ON item (folder_id,flag_update)
CREATE INDEX IDX_item_rid ON item (folder_id,rid)
CREATE TABLE wm_metadata (item_key VARCHAR(128), item_value VARCHAR(128))
INSERT INTO wm_metadata (item_key, item_value) VALUES ('db_version', '26')